---
title: "回归、匹配和psm"
date: "2023-09-25"
categories: [causal inference]
---

回归、匹配和psm主要用于观察性数据的因果推断。我们关心的是，某个操作，比如是否发券、是否参加培训、是否使用某项药物/化妆品（这里都是二分的，只有是和否两个选项）。

比如，我们想知道使用化妆品是否能改善皮肤状态。

- 如果有A/B实验，直接用 「使用化妆品的群体的皮肤的平均值 - 使用化妆品的群体的皮肤的平均值」，就可以衡量化妆品的效果了。

- 如果没有做实验，在观察性数据里， 「使用化妆品的群体的皮肤的平均值 - 使用化妆品的群体的皮肤的平均值」不能代表「化妆品的效果」，因为

    - 经济条件比较好的群体，或者生活习惯更健康的群体的皮肤状态更好（除「是否使用化妆品」之外的其他变量X，但会影响y)
    
    - 经济条件比较好的群体，或者生活习惯更健康的群体更可能使用化妆品（这就是倾向性得分，个体属于实验组/处理组的概率）
    
- 回归、匹配和psm都可以解决这个问题

  - 回归： Y皮肤状态 ~ 是否使用化妆品 + 经济条件 + 生活习惯， 是否使用化妆品的系数就是控制了经济条件 + 生活习惯的差异后，使用化妆品对皮肤的影响
  - 匹配：
      - 把人群按「经济条件 + 生活习惯」分层，
      - 在每个层内，计算 层内处理效应 = 「使用化妆品的群体的皮肤的平均值 - 使用化妆品的群体的皮肤的平均值」
      - 整体处理效应 =  每个层的占比 * 层内处理效应
      - 匹配的优势：直接 + 易于理解/实现 + 容易检查实验组对照组是否同质

      - 如果有很多个控制变量，层可能会太多，可以做近似匹配

          - 对处理组的每个个体，考虑控制变量x0, x1, x2, ... xm
          - 在控制组中，找最接近的个体。最接近用距离来衡量，
              - 欧式距离：比如(x0‘ - x0) ** 2 + (x1‘ - x1) ** 2 + ...
              - 马氏距离：标准化后再算距离

  - psm:

      - 用控制变量预测是否使用化妆品， 是否使用化妆品 ～ 经济条件 + 生活习惯，得到每个用户使用化妆品的概率ps
      - 直接用psm加权
        - 对每个个体
        - 如果是处理组，Y / ps, 如果是对照组 Y / (1 - ps)
        - 求平均，就是使用化妆品的处理效应
      - 或者psm + 匹配法（更常见）
        - 按ps排序后，分层n个层
        - 在每个层内，计算 层内处理效应 = 「使用化妆品的群体的皮肤的平均值 - 使用化妆品的群体的皮肤的平均值」
        - 整体处理效应 =  每个层的占比 * 层内处理效应

      - psm相对于回归的优势
        - 对控制变量降维，比多个控制变量变成了单一的倾向性得分ps
        - 避免在回归中，通过添加/移除控制变量来操纵结论，因为psm是对「是否是处理组」回归的, 而不是直接对y回归

    
        




